# Book settings
title: Child Allowance
author: UBI Center
logo: _static/ubi_center_logo.png

html:
  use_edit_page_button      : true
  use_repository_button     : true
  use_issues_button         : true
  google_analytics_id       : "UA-138885251-1"
  baseurl                   : "https://covid.ubicenter.org"

repository:
  url: https://github.com/UBICenter/childallowance
  path_to_book: jb

execute:
  execute_notebooks: 'cache'
  timeout: None